# -*- coding: utf-8 -*-
"""faiss_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tomTqQsJK8OIO-frDDyuKn0tyPGsh1EE
"""

import re
from symspellpy import Verbosity

def autocorrect(query,sym):
  words=re.findall(r"[a-zA-Z]+",query)
  corrected_words=[]
  for w in words:
    correct=sym.lookup(w,Verbosity.CLOSEST,max_edit_distance=2)
    if correct:
      corrected_words.append(correct[0].term)
    else:
      corrected_words.append(w)
  return corrected_words

def stop_words(query):
  query=re.findall(r"[a-zA-Z]+",query)
  stopwords = ["have","think","how","why","I","a","about","also","am","an","and","are","at","be","being","but","can","could","explain","feel","for","from","had","has","have","i","in","is","just","like","me","my","of","on","or","please","tell","the","think","to","was","were","what","with","would","you",",","."]
  query=[w for w in query if w not in stopwords]
  return (" ").join(query).strip()

#search function
def search(query,vector_db,reranker,sym):
  query=query.lower().strip()
  token=stop_words(query)
  token1=autocorrect(token,sym)
  for i,j in zip(list(token.split()),token1):
    query=query.replace(i,j)
  data=[]
  for i in token1:
    result=vector_db.similarity_search(i,k=1)
    data.append(f"""{result[0].metadata}
    Disease info: {result[0].page_content}\n""")

  pairs=[[query,des] for des in data]
  scores=reranker.predict(pairs)
  ranked=sorted(zip(scores,data),reverse=True)
  ranked=ranked[0:3]
  ranked=[i[1] for i in ranked]
  return ranked,query