# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwZDHf5Oc5k0ukb_x5uMgf0f5SRNj1_6
"""

import sys
import os
from PyQt6.QtWidgets import QApplication
from PyQt6.QtCore import pyqtSignal, QObject, QThread

from ui_chat import ChatWindow
import pipeline


class Loader(QObject):
    """Background model loader running inside a QThread."""
    finished = pyqtSignal()

    def load_models(self):
        try:
            _ = pipeline.final("hello")  # triggers model loading
        except Exception as e:
            print("Error while loading models:", e)

        self.finished.emit()


def main():
    app = QApplication(sys.argv)

    # --------------------------------------------------------------
    # Load style.qss (Dark Theme)
    # --------------------------------------------------------------
    try:
        style_path = os.path.join(os.path.dirname(__file__), "style.qss")
        with open(style_path, "r") as f:
            app.setStyleSheet(f.read())
        print("Style loaded successfully.")
    except Exception as e:
        print("Could not load style.qss:", e)

    # --------------------------------------------------------------
    # Create main chat window immediately
    # --------------------------------------------------------------
    chat_window = ChatWindow()
    chat_window.show()

    # --------------------------------------------------------------
    # Background QThread model loader
    # --------------------------------------------------------------
    thread = QThread()
    loader = Loader()

    loader.moveToThread(thread)
    thread.started.connect(loader.load_models)

    # Clean up after loading finishes
    loader.finished.connect(thread.quit)
    loader.finished.connect(loader.deleteLater)
    thread.finished.connect(thread.deleteLater)

    # Start model loading
    thread.start()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()