# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnLvFpZHr0d-bqrUtDWE2JP9l8paLxBc
"""

from translation import detect_language, translate_to_english, translate_to_regional
from load_models import load_dictionary, load_minillm, load_crossencoder, load_qwen, load_faiss, load_M2M100
from faiss_search import autocorrect, stop_words, search
from qwen_inference import normal_response, vague_response, response, detect_intent

sym=load_dictionary("./models/Name-Symptom.txt")
embeddings,intent_model=load_minillm("./models/all-MiniLM-L6-v2")
reranker=load_crossencoder("./models/cross_encoder")
vector_db=load_faiss("./models/faiss_store",embeddings)
llm=load_qwen("./models/Qwen3-0.6B-Medical-Expert-abliterated.Q8_0.gguf")
model,tokenizer=load_M2M100("./models/m2m100_418M")

def final(text):
  prompt=translate_to_english(text,tokenizer,model)
  intent=detect_intent(prompt,intent_model)

  if intent=="vague":
    res=vague_response(prompt,llm)
  elif intent=="normal":
    res=normal_response(prompt,llm)
  else:
    context,prompt=search(prompt,vector_db,reranker,sym)
    res = response(prompt,llm,context)

  result=translate_to_regional(text,res,tokenizer,model)
  return result