# -*- coding: utf-8 -*-
"""qwen_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eDgVdwjQ_aP8iSaIwDsal6YwR3J7raz3
"""

from sentence_transformers import util

def detect_intent(text,intent_model):
  examples = {
      "normal": [
          "hi", "hello", "hey", "hey there", "hi bro", "hello friend",
          "good morning", "good evening", "good night",
          "how are you", "how r u", "what's up", "wassup",
          "nice to meet you", "pleased to meet you",
          "thank you", "thanks", "thanks a lot", "thx",
          "ok", "okay", "alright", "cool",
          "bye", "goodbye", "see you", "see ya",
          "take care", "have a nice day"
      ],

      "vague": [
          "help", "please help", "need help",
          "i don't know", "idk", "not sure",
          "what should i do", "what can i do",
          "can you tell me something",
          "tell me", "say something",
          "not feeling good",
          "i feel bad",
          "feeling weird",
          "something feels off",
          "something is wrong",
          "i am uncomfortable",
          "i am confused",
          "i feel strange",
          "feels odd",
          "h", "hh", "hmm", "hmmm",
          "??", "...", "uh",
          "lol", "haha", "hahaha", "ahahaha",
          "fhagsda", "asdjkl", "qwerty",
          "random text",
          "nothing",
          "dont know what to say"
      ],

      "medical": [
          "fever", "high fever", "low fever",
          "headache", "severe headache",
          "body pain", "muscle pain",
          "chest pain", "chest discomfort",
          "stomach ache", "abdominal pain",
          "back pain", "joint pain",
          "vomiting", "nausea",
          "diarrhea", "loose motions",
          "constipation",
          "cough", "dry cough", "wet cough",
          "cold", "runny nose",
          "sore throat",
          "breathing problem", "shortness of breath",
          "diabetes", "high blood sugar",
          "blood pressure", "high bp", "low bp",
          "flu", "viral infection",
          "infection", "bacterial infection",
          "allergy", "skin allergy",
          "skin rash", "itching on skin",
          "asthma",
          "thyroid problem",
          "anemia",
          "covid", "covid symptoms",
          "cancer",
          "feeling feverish",
          "pain in chest",
          "pain in stomach",
          "burning sensation while urinating",
          "frequent urination",
          "loss of appetite",
          "feeling weak",
          "dizziness",
          "fainting",
          "swelling",
          "redness on skin"
      ]
  }


  example_embeddings={} #embeddings to perform similarity serach with
  for label,exp in examples.items():
    example_embeddings[label]=intent_model.encode(exp,convert_to_tensor=True)

  simi={}
  text_embed = intent_model.encode(text, convert_to_tensor=True)
  for label, emb in example_embeddings.items():
    simi[label]= util.cos_sim(text_embed,emb).max().item()

  return max(simi,key=simi.get)

def response(query,llm,context):
  prompt =f"""
  You are QwenVeda, a professional multilingual medical assistant.
  You provide structured, concise, and verified medical information.
  Do NOT provide personal diagnosis; always include cautionary notes.

  Use the following format exactly:

  ----START----
  **Introduction:**
  - One or two sentences summarizing the condition.

  **Causes:**
  - Bullet point 1
  - Bullet point 2
  - Bullet point 3 (if applicable)

  **Symptoms:**
  - Bullet point 1
  - Bullet point 2
  - Bullet point 3 (if applicable)

  **Treatment / Management:**
  - Bullet point 1
  - Bullet point 2
  - Bullet point 3 (if applicable)

  **Precautions:**
  - Bullet point 1
  - Bullet point 2
  - Bullet point 3 (if applicable)

  **References:**
  - List URLs or trusted sources provided in context
  ----STOP----

  Here is the verified context from your database:

  {context}

  **Question:**
  {query}

  Answer using the exact format above. Keep it concise, professional, and structured."""

  res = llm(prompt=prompt, max_tokens=250, temperature=0.0, top_p=0.9,repeat_penalty = 1.1,echo=False,presence_penalty=1)
  res=res["choices"][0]["text"]

  if "----START----" in res:
    res=res.split("----START----")[1].strip()
  if "----END----" in res:
    res=res.split("----END----")[0].strip()
  if "----STOP----" in res:
    res=res.split("----STOP----")[0].strip()

  res += "\n\n**Note:**\nThis information is for educational purposes only. Please consult a qualified healthcare professional for medical advice."
  return res

def vague_response(query,llm):
  prompt =f"""
You are QwenVeda, a **professional multilingual medical assistant**.
The user's message is vague, incomplete, or unclear.
Your task is to **politely and professionally request clarification**.
Do NOT provide medical advice yet. Only ask for missing or ambiguous information.
Generate **3–4 bullet points only**, focusing on the most essential clarifications.

--- EXAMPLE ---

User's message: "I feel unwell, what should I do?"
Clarification Request:
- Could you specify your main symptom(s)? e.g., fever, headache, nausea
- How long have you been experiencing these symptoms?
- Are there any underlying conditions or medications we should know about?

--- END EXAMPLE ---

### User's message:
{query}

### Output Format:
----Start----
**Clarification Request:**
- Bullet point 1 (specific question about missing info)
- Bullet point 2 (if applicable)
- Optional: one concise sentence politely asking for clarification
----STOP----

Answer using the exact format above. Keep it concise, professional, and structured.
"""

  res=llm(prompt=prompt, max_tokens=100,temperature=0.0, top_p=0.90, echo=False,presence_penalty=1,repeat_penalty=1.1)
  res=res["choices"][0]["text"]
  if "----Start----" in res:
    res=res.split("----Start----")[1].strip()
  # if "-----" in res:
  #   res=res.split("-----")[1]
  # if "--- END OF OUTPUT" in res:
  #   res=res.split("--- END OF OUTPUT")[0]
  if "----STOP----" in res:
    res=res.split("----STOP----")[0].strip()
  if "----END----" in res:
    res=res.split("----END----")[0].strip()
  if "----" in res:
    res=res.split("----")[0].strip()
  return res

def normal_response(query,llm):
  prompt=f"""
You are QwenVeda, a professional multilingual medical assistant.
The user has sent a casual or normal greeting message that does not require medical advice.

Your task:
- Respond politely and briefly.
- Keep it concise (1–2 sentences).
- Do NOT provide medical advice or ask for symptoms.
- Maintain a neutral, professional tone.

--- EXAMPLES ---

User: Hi
Response: Hello! How can I assist you with your healthcare questions today?

User: Hello
Response: Hi there! I am here to help with any health-related queries you may have.

User: Hey
Response: Hello! How can I assist you today?

--- END EXAMPLES ---

### User's message:
{query}

Response:
"""
  res=llm(prompt=prompt, max_tokens=50,temperature=0.0, top_p=0.90, echo=False,presence_penalty=1,repeat_penalty=1.1)
  res=res["choices"][0]["text"]
  if "### Output Format:" in res:
    res=res.split("### Output Format:")[1].strip()
  if "Response:" in res:
    res=res.split("Response:")[1].strip()
  if "--- END RESPONSES ---" in res:
    res=res.split("--- END RESPONSES ---")[0].strip()
  if "----STOP----" in res:
    res=res.split("----STOP----")[0].strip()
  if "--- END RESPONSES" in res:
    res=res.split("--- END RESPONSES")[0].strip()
  return res