# -*- coding: utf-8 -*-
"""ui_chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_CA7J-ELab-MoYnovJSUsk0ZWTNMM6f
"""

import sys
import os
import threading
import time
import markdown
from datetime import datetime
from PyQt6.QtWidgets import QGraphicsOpacityEffect
from PyQt6.QtCore import QPropertyAnimation, QParallelAnimationGroup, QPoint

from PyQt6.QtCore import Qt, pyqtSignal, QObject, QTimer
from PyQt6.QtGui import QFont, QPixmap
from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QScrollArea, QFrame
)

sys.path.append(os.path.dirname(os.path.dirname(__file__)))
import pipeline


# ======================================================
# Streaming Worker
# ======================================================
class InferenceWorker(QObject):
    progress = pyqtSignal(str)
    finished = pyqtSignal(str)

    def __init__(self, text):
        super().__init__()
        self.text = text

    def run(self):
        full = pipeline.final(self.text)
        partial = ""
        for word in full.split():
            partial += word + " "
            self.progress.emit(partial.strip())
            time.sleep(0.018)
        self.finished.emit(full)


def md(text: str) -> str:
    return markdown.markdown(
        text,
        extensions=["nl2br", "fenced_code", "sane_lists"]
    )


def timestamp() -> str:
    return datetime.now().strftime("%H:%M")


# ======================================================
# Main Window
# ======================================================
class ChatWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("QwenVeda")
        self.setMinimumSize(1150, 820)
        self.setStyleSheet("background:#faf9f7;")

        self.current_bot = None
        self.current_bot_raw = ""

        self.typing_wrapper = None
        self.typing_label = None
        self.typing_timer = None
        self.typing_index = 0

        central = QWidget()
        self.setCentralWidget(central)
        root = QVBoxLayout(central)
        root.setContentsMargins(0, 0, 0, 0)
        root.setSpacing(0)

        # ================= Header =================
        header = QWidget()
        header_layout = QHBoxLayout(header)
        header_layout.setContentsMargins(48, 24, 48, 10)
        header_layout.setSpacing(12)

        # ---- Logo ----
        logo = QLabel()
        logo_path = os.path.join(
            os.path.dirname(__file__),
            "assets",
            "logo.png"
        )

        if os.path.exists(logo_path):
            pixmap = QPixmap(logo_path)
            pixmap = pixmap.scaled(
                70, 70,
                Qt.AspectRatioMode.KeepAspectRatio,
                Qt.TransformationMode.SmoothTransformation
            )
            logo.setPixmap(pixmap)

        logo.setFixedSize(70, 70)
        logo.setAlignment(Qt.AlignmentFlag.AlignVCenter)

        # ---- Title ----
        title = QLabel("QwenVeda")
        title.setFont(QFont("Segoe UI Variable", 20, QFont.Weight.Medium))
        title.setStyleSheet("color:#1f1f1f;")
        title.setAlignment(Qt.AlignmentFlag.AlignVCenter)

        header_layout.addWidget(logo)
        header_layout.addWidget(title)
        header_layout.addStretch()

        root.addWidget(header)

        # ================= Scroll Area =================
        self.scroll = QScrollArea()
        self.scroll.setWidgetResizable(True)
        self.scroll.setStyleSheet("border:none;")

        self.page = QWidget()
        self.page_layout = QVBoxLayout(self.page)
        self.page_layout.setAlignment(Qt.AlignmentFlag.AlignTop)
        self.page_layout.setSpacing(32)
        self.page_layout.setContentsMargins(0, 30, 0, 160)

        self.scroll.setWidget(self.page)
        root.addWidget(self.scroll)

        # ================= Input Bar =================
        input_wrap = QWidget()
        input_layout = QHBoxLayout(input_wrap)
        input_layout.setContentsMargins(0, 0, 0, 28)

        input_container = QFrame()
        input_container.setFixedWidth(760)
        input_container.setStyleSheet("""
            QFrame {
                background:white;
                border-radius:20px;
                border:1px solid #e3e3e3;
            }
        """)

        ic = QHBoxLayout(input_container)
        ic.setContentsMargins(18, 14, 18, 14)

        self.input = QLineEdit()
        self.input.setPlaceholderText("Ask anything")
        self.input.setFont(QFont("Segoe UI", 12))
        self.input.setStyleSheet("""
            QLineEdit {
                border:none;
                background:transparent;
                color:#111;
                padding:6px;
            }
        """)
        self.input.returnPressed.connect(self.send)

        send = QPushButton("➤")
        send.setFixedSize(48, 48)
        send.setFont(QFont("Segoe UI Symbol", 15, QFont.Weight.Bold))
        send.setStyleSheet("""
            QPushButton {
                background:black;
                color:white;
                border-radius:23px;
                padding:0px;
                qproperty-alignment: AlignCenter;
            }
            QPushButton:hover {
                background:#111;
            }
        """)
        send.clicked.connect(self.send)

        ic.addWidget(self.input, 1)
        ic.addWidget(send)

        input_layout.addStretch()
        input_layout.addWidget(input_container)
        input_layout.addStretch()

        root.addWidget(input_wrap)


    # UI blocks, typing indicator, messaging, scrolling
    # remain EXACTLY as you already validated.

    # ==================================================
    # UI Blocks
    # ==================================================
    def add_user_pill(self, text: str):
        pill = QLabel(text)
        pill.setFont(QFont("Segoe UI", 11))
        pill.setWordWrap(True)
        pill.setStyleSheet("""
            QLabel {
                background:#eeeeee;
                color:#333;
                padding:10px 16px;
                border-radius:16px;
            }
        """)

        wrapper = QWidget()
        wrapper_layout = QHBoxLayout(wrapper)
        wrapper_layout.addStretch()

        column = QWidget()
        column.setFixedWidth(720)
        col_layout = QHBoxLayout(column)
        col_layout.setContentsMargins(0, 0, 0, 0)

        col_layout.addStretch()
        col_layout.addWidget(pill)

        wrapper_layout.addWidget(column)
        wrapper_layout.addStretch()

        self.page_layout.addWidget(wrapper)
        self.animate_appear(wrapper)
        QTimer.singleShot(10, self.scroll_to_bottom)

    def add_bot_block(self, text: str = ""):
        self.current_bot_raw = text

        wrapper = QWidget()
        row = QHBoxLayout(wrapper)
        row.addStretch()

        bubble = QLabel()
        bubble.setFixedWidth(720)
        bubble.setWordWrap(True)
        bubble.setTextInteractionFlags(
            Qt.TextInteractionFlag.TextSelectableByMouse
        )
        bubble.setStyleSheet("""
            QLabel {
                background:#f3f3f3;
                color:#111;
                padding:16px 18px;
                border-radius:16px;
                font-size:14px;
                line-height:1.55;
            }
        """)
        bubble.setText(md(text))
        self.current_bot = bubble

        time_label = QLabel(timestamp())
        time_label.setFont(QFont("Segoe UI", 9))
        time_label.setStyleSheet("color:#777; margin-top:6px;")

        copy_btn = QPushButton("Copy")
        copy_btn.setFixedWidth(56)
        copy_btn.setStyleSheet("""
            QPushButton {
                background:#e5e5e5;
                border:none;
                padding:4px;
                border-radius:6px;
                font-size:10px;
            }
            QPushButton:hover {
                background:#d5d5d5;
            }
        """)
        copy_btn.clicked.connect(
            lambda: QApplication.clipboard().setText(self.current_bot_raw)
        )

        v = QVBoxLayout()
        v.addWidget(bubble)
        v.addWidget(time_label, alignment=Qt.AlignmentFlag.AlignLeft)
        v.addWidget(copy_btn, alignment=Qt.AlignmentFlag.AlignLeft)

        row.addLayout(v)
        row.addStretch()

        self.page_layout.addWidget(wrapper)
        self.animate_appear(wrapper)


    def animate_appear(self, widget: QWidget):
        # Opacity effect
        opacity = QGraphicsOpacityEffect(widget)
        widget.setGraphicsEffect(opacity)
        opacity.setOpacity(0)

        fade = QPropertyAnimation(opacity, b"opacity")
        fade.setDuration(180)
        fade.setStartValue(0)
        fade.setEndValue(1)

        # Slide up effect
        start_pos = widget.pos() + QPoint(0, 8)
        end_pos = widget.pos()

        slide = QPropertyAnimation(widget, b"pos")
        slide.setDuration(180)
        slide.setStartValue(start_pos)
        slide.setEndValue(end_pos)

        anim = QParallelAnimationGroup(widget)
        anim.addAnimation(fade)
        anim.addAnimation(slide)

        # Keep reference so Qt doesn't GC it
        widget._appear_anim = anim
        anim.start()


    # ==================================================
    # Typing Indicator (unchanged)
    # ==================================================
    def show_typing(self):
        if self.typing_wrapper:
            return

        self.typing_states = [
            "t", "ty", "typ", "typi", "typin",
            "typing", "typing.", "typing..", "typing..."
        ]

        self.typing_index = 0

        self.typing_label = QLabel("typing")
        self.typing_label.setFont(QFont("Segoe UI", 12))
        self.typing_label.setStyleSheet("""
            QLabel {
                background:#f3f3f3;
                color:#555;
                padding:10px 16px;
                border-radius:16px;
            }
        """)

        column = QWidget()
        column.setFixedWidth(720)
        col = QHBoxLayout(column)
        col.addWidget(self.typing_label)
        col.addStretch()

        self.typing_wrapper = QWidget()
        wrap = QHBoxLayout(self.typing_wrapper)
        wrap.addStretch()
        wrap.addWidget(column)
        wrap.addStretch()

        self.page_layout.addWidget(self.typing_wrapper)
        self.scroll_to_bottom()

        self.typing_timer = QTimer()
        self.typing_timer.timeout.connect(self.update_typing)
        self.typing_timer.start(120)

    def update_typing(self):
        self.typing_label.setText(self.typing_states[self.typing_index])
        self.typing_index = (self.typing_index + 1) % len(self.typing_states)

    def hide_typing(self):
        if self.typing_timer:
            self.typing_timer.stop()
            self.typing_timer = None

        if self.typing_wrapper:
            self.typing_wrapper.setParent(None)
            self.typing_wrapper = None

    # ==================================================
    # Messaging
    # ==================================================
    def send(self):
        text = self.input.text().strip()
        if not text:
            return

        self.add_user_pill(text)
        self.input.clear()
        self.input.setDisabled(True)

        self.show_typing()

        self.worker = InferenceWorker(text)
        self.worker.progress.connect(self.stream)
        self.worker.finished.connect(self.finish)

        threading.Thread(target=self.worker.run, daemon=True).start()

    def stream(self, partial: str):
        self.hide_typing()
        self.current_bot_raw = partial

        if not self.current_bot:
            self.add_bot_block(partial)
        else:
            self.current_bot.setText(md(partial))
            self.current_bot.adjustSize()

        QTimer.singleShot(10, self.scroll_to_bottom)

    def finish(self, final: str):
        self.hide_typing()
        self.current_bot_raw = final

        if self.current_bot:
            self.current_bot.setText(md(final))
            self.current_bot.adjustSize()

        self.current_bot = None
        self.input.setDisabled(False)
        self.input.setFocus()

        QTimer.singleShot(10, self.scroll_to_bottom)

    def scroll_to_bottom(self):
        bar = self.scroll.verticalScrollBar()
        bar.setValue(bar.maximum())


# ======================================================
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = ChatWindow()
    window.show()
    sys.exit(app.exec())